site_name: Jacob Rider's Personal Portfolio
site_url: https://Grow-Myelin.github.io
site_description: A brief description about you.
site_author: Jacob Rider

theme:
  name: 'minty'
  features:
    - instant.loading
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Experience: experience.md
  - Education: education.md
  - Skills: skills.md
  - Projects:
      - 'TI4 Combat Simulator': ti4_combat_simulator.md
      - 'Baseball Pitch Predictor': 'baseball_pitch_predictor.md'
      - 'Probabilistic Programming Tools': 'prob_prog_tools.md'
      - 'Data Tools for Economic Research': 'data_tools.md'
  - Contact: contact.md
